on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest  # Or your preferred runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the actions/checkout action to check out the repository
        with:
          fetch-depth: 0  # Fetch all branches and tags

      - name: Deploy to gh-pages branch
        run: |
          # Configure git user
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create and checkout a new gh-pages branch
          git checkout --orphan gh-pages
          
          # Remove all files except dist
          git rm -rf .
          
          # Copy dist contents to root
          cp -r dist/* .
          rm -rf dist
          
          # Stage and commit
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages